"""added spare part table

Revision ID: 12edcac38f07
Revises: f882687a8231
Create Date: 2024-09-25 16:57:38.901304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '12edcac38f07'
down_revision: Union[str, None] = 'f882687a8231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spare_parts', 'unit_price',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spare_parts', 'unit_price',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
