"""added spare part table

Revision ID: 1586348acca7
Revises: b4c76a0ea3fe
Create Date: 2024-09-25 17:36:04.603134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1586348acca7"
down_revision: Union[str, None] = "b4c76a0ea3fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spare_parts", sa.Column("status", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spare_parts", "status")
    # ### end Alembic commands ###
