"""change in ticket assigned

Revision ID: 533f0add301a
Revises: 68ff7311ecd0
Create Date: 2024-09-23 14:22:35.548380

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "533f0add301a"
down_revision: Union[str, None] = "68ff7311ecd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ticket_assign", sa.Column("assigned_by_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint("ticket_assign_ibfk_2", "ticket_assign", type_="foreignkey")
    op.create_foreign_key(None, "ticket_assign", "user", ["assigned_by_id"], ["id"])
    op.drop_column("ticket_assign", "service_head_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ticket_assign",
        sa.Column(
            "service_head_id", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "ticket_assign", type_="foreignkey")
    op.create_foreign_key(
        "ticket_assign_ibfk_2", "ticket_assign", "user", ["service_head_id"], ["id"]
    )
    op.drop_column("ticket_assign", "assigned_by_id")
    # ### end Alembic commands ###
