"""Added ticketAssign table just created after bugging

Revision ID: 68ff7311ecd0
Revises: 99bd38194afa
Create Date: 2024-09-23 11:55:33.041073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68ff7311ecd0"
down_revision: Union[str, None] = "99bd38194afa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket_assign",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=True),
        sa.Column("service_head_id", sa.Integer(), nullable=True),
        sa.Column("service_engineer_id", sa.Integer(), nullable=True),
        sa.Column("assigned_date", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["service_engineer_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_head_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "ticket_rejected", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ticket_rejected", "created_at")
    op.drop_table("ticket_assign")
    # ### end Alembic commands ###
