"""changes in  work report table

Revision ID: 6a325274f658
Revises: f5cf19028fd2
Create Date: 2024-09-26 17:06:47.015811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6a325274f658"
down_revision: Union[str, None] = "f5cf19028fd2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "work_report",
        "report_date",
        existing_type=mysql.DATETIME(),
        type_=sa.Date(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "work_report",
        "report_date",
        existing_type=sa.Date(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
