"""changes in  ticket process

Revision ID: 76655c5a480f
Revises: 649bd93dc292
Create Date: 2024-09-25 13:41:42.476180

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76655c5a480f"
down_revision: Union[str, None] = "649bd93dc292"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ticket_process",
        sa.Column("problem_description", sa.String(length=255), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ticket_process", "problem_description")
    # ### end Alembic commands ###
