"""Added ticketAssign table

Revision ID: 85ad2cb54668
Revises: aa4cfec37e1c
Create Date: 2024-09-23 11:49:28.131145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85ad2cb54668"
down_revision: Union[str, None] = "aa4cfec37e1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
