"""added empolyee expense tables

Revision ID: a797defeaf2e
Revises: 6a325274f658
Create Date: 2024-09-26 22:24:09.235643

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a797defeaf2e"
down_revision: Union[str, None] = "6a325274f658"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "travel_expense_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_engineer_ID", sa.Integer(), nullable=True),
        sa.Column("ticket_ID", sa.Integer(), nullable=True),
        sa.Column("expense_details", sa.String(length=255), nullable=False),
        sa.Column("total_amount", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("approval_status", sa.String(length=50), nullable=True),
        sa.Column("approved_by", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_engineer_ID"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_ID"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "travel_expense_rejection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("rejected_by_id", sa.Integer(), nullable=False),
        sa.Column("rejection_reason", sa.String(length=255), nullable=False),
        sa.Column("rejected_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rejected_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["travel_expense_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("travel_expense_rejection")
    op.drop_table("travel_expense_reports")
    # ### end Alembic commands ###
