"""Added ticketAssign table

Revision ID: aa4cfec37e1c
Revises: e1ebd1088c46
Create Date: 2024-09-23 11:49:01.493331

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa4cfec37e1c"
down_revision: Union[str, None] = "e1ebd1088c46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
