"""Changed password size

Revision ID: c5acc9c598e8
Revises: b934493fb0f4
Create Date: 2024-09-19 15:26:49.408525

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "c5acc9c598e8"
down_revision: Union[str, None] = "b934493fb0f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password",
        existing_type=sa.String(length=64),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
