"""createdn ticket process

Revision ID: d48fd1eae926
Revises: 533f0add301a
Create Date: 2024-09-25 11:27:07.015499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d48fd1eae926"
down_revision: Union[str, None] = "533f0add301a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket_process",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("service_engineer_id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.String(length=50), nullable=False),
        sa.Column("excepted_complete_date", sa.DateTime(), nullable=False),
        sa.Column("actual_complete_date", sa.DateTime(), nullable=False),
        sa.Column("spare_parts_required", sa.Boolean(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["service_engineer_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket_process")
    # ### end Alembic commands ###
