"""added is active to User Table

Revision ID: de1ec3f1c8be
Revises: c5acc9c598e8
Create Date: 2024-09-19 15:36:21.753136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de1ec3f1c8be"
down_revision: Union[str, None] = "c5acc9c598e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_active")
    # ### end Alembic commands ###
