"""changes in ticket process

Revision ID: ecd2385e9a35
Revises: d8b12eeb1d93
Create Date: 2024-09-27 15:08:42.079723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ecd2385e9a35'
down_revision: Union[str, None] = 'd8b12eeb1d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_process', sa.Column('labour_cost', sa.Float(), nullable=True))
    op.drop_column('ticket_process', 'cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_process', sa.Column('cost', mysql.FLOAT(), nullable=True))
    op.drop_column('ticket_process', 'labour_cost')
    # ### end Alembic commands ###
